services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/discgolf
      - ENVIRONMENT=development
    depends_on:
      - db
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fastputt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8085:8085" # Changed from "8085:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always
    command: npm run serve
    networks:
      - fastputt-network

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=discgolf
    ports:
      - "5432:5432"
    restart: always
    networks:
      - fastputt-network

volumes:
  postgres_data:

networks:
  fastputt-network:
    driver: bridge

